### ISSUE TITLE
onChangeItem

### ISSUE THREAD

**Issue by saeedhabibi** [onmotion/react-native-autocomplete-dropdown#1]
Is there no #onchangeitem option in َAutocompleteDropdown?
Help if you can
Thanks

**Comment by onmotion** [comment]
Hi!

Maybe you are looking for onSelectItem?

**Comment by saeedhabibi** [comment]
Hi

Thank you for your time

No, it does not work when I use it.
But it works onChangeText when I type in input.
See these. I hope it is helpful.
![Screenshot 2021-05-11 110706-1](https://user-images.githubusercontent.com/15168601/117771131-06203f00-b24b-11eb-95d2-f83baafa21a4.jpg)
![Screenshot 2021-05-11 110605](https://user-images.githubusercontent.com/15168601/117771154-0d474d00-b24b-11eb-9c02-a1aaf3354e7c.jpg)
![Screenshot 2021-05-11 110824-3](https://user-images.githubusercontent.com/15168601/117771350-3ff14580-b24b-11eb-902e-3559a535ba48.jpg)
![Screenshot 2021-05-11 110949-4](https://user-images.githubusercontent.com/15168601/117771368-441d6300-b24b-11eb-9fea-65707236b0b8.jpg)
![Screenshot 2021-05-11 111041-5](https://user-images.githubusercontent.com/15168601/117771374-45e72680-b24b-11eb-9953-47d37621c161.jpg)
![InkedScreenshot 2021-05-11 110824-3](https://user-images.githubusercontent.com/15168601/117771379-48498080-b24b-11eb-8904-1e1eb43a31fb.jpg)

**Comment by saeedhabibi** [comment]
onChangeText={title => this.setState({dataSet: title})}   //It works.

 onSelectItem={item => this.setState({dataSet: item})}  //Does not work.

**Comment by saeedhabibi** [comment]
onSelectItem={item => console.log(item)}  =====> // It does not show 
![Screenshot 2021-05-11 121151](https://user-images.githubusercontent.com/15168601/117778984-78951d00-b253-11eb-9e35-71787aab634e.jpg)
![Screenshot 2021-05-11 122423](https://user-images.githubusercontent.com/15168601/117779348-d88bc380-b253-11eb-82ba-bb3af17a34c6.jpg)



`**this.setState({dataSet: item.title})**`     

**This code also gives this error.**


![Screenshot 2021-05-11 122914](https://user-images.githubusercontent.com/15168601/117780112-8f883f00-b254-11eb-8ba6-6f60379d886d.jpg)

![Screenshot 2021-05-11 121701](https://user-images.githubusercontent.com/15168601/117780149-9a42d400-b254-11eb-88bd-f9a88507e38b.jpg)

**Comment by onmotion** [comment]
add check for null `item.title ?? null`

or if you want set the object:
```js
this.setState(prevState => ({
    dataSet: {         
       ...item
    }
}))
```

Also try to use React Native Debugger console for see all data (not only stringified [Object object])

**Comment by onmotion** [comment]
from real case:

```js
onSelectItem={(item) => {
              item && setNewOidValue(item.id)
            }}
```

**Comment by saeedhabibi** [comment]
update ====>


this.setState(prevState => ({ dataSet: { ...item } }))

I wrote your way, but there is the same problem. This code also gives this error.
Of course, I do not know if it is true or not.

![Screenshot 2021-05-11 135401](https://user-images.githubusercontent.com/15168601/117792269-61106100-b260-11eb-83ce-e1efc2325afa.jpg)

**Comment by onmotion** [comment]
This like js works. You must add check *item* to null or undefined. For that add `item &&` at the top of your closure.

**Comment by onmotion** [comment]
ur welcome
