### ISSUE TITLE
Disable chevron animation

### ISSUE THREAD

**Issue by nikhiysham** [onmotion/react-native-autocomplete-dropdown#10]
How to disable chevron animation?

**Comment by saeedhabibi** [comment]
Hi
show clear button =>      showClear={false}
show chevron (open/close) button =>        showChevron={false}

**Comment by onmotion** [comment]
Now it can be solved with custom `RightIconComponent`
Please follow the example https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/example/components/CustomRightIconExample.js
