### ISSUE TITLE
content not clean after component unmounted, So there is an issue where content is rendered on top of the thread even though the component has been unmounted

### ISSUE THREAD

**Issue by soleh45** [onmotion/react-native-autocomplete-dropdown#112]
<img width="1439" alt="Screenshot 2024-03-04 at 22 43 07" src="https://github.com/onmotion/react-native-autocomplete-dropdown/assets/93110828/903726ba-c087-46ab-9eab-045c57bfab95">

**Comment by onmotion** [comment]
#114
