### ISSUE TITLE
Bug: Unable to select Dropdown items on Android

### ISSUE THREAD

**Issue by IPWright83** [onmotion/react-native-autocomplete-dropdown#12]
I'm getting an issue on Android where while the dropdown appears, I can't interact with the dropdown selections at all. It seems to occur whenever I wrap the control in a `<View>` and apply any styling to that view.

Here is a snack to demonstrate the issue https://snack.expo.dev/@ipwright83/react-native-autocomplete-dropdown. Running on Android you're unable to interact with the dropdown (unless you comment out `borderColor` and `borderWidth`) on lines 53-54. 

This only seems to affect Android, it works correctly on iOS.

Here's some code to reproduce:

```
import React, { Node, useState } from 'react';
import {
  Platform,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import { Colors } from 'react-native/Libraries/NewAppScreen';
import { AutocompleteDropdown } from 'react-native-autocomplete-dropdown';

const App: () => Node = () => {
  const styles = getStyles();
  const [selectedItem, setSelectedItem] = useState(null);

  return (
    <React.Fragment>
      <View style={styles.spacer} />
      <View style={styles.container}>
        <AutocompleteDropdown
          clearOnFocus={false}
          closeOnBlur={true}
          initialValue={{ id: '2' }} // or just '2'
          dataSet={[
            { id: '1', title: 'Alpha' },
            { id: '2', title: 'Beta' },
            { id: '3', title: 'Gamma' },
          ]}
        />
        <Text style={{ color: '#668', fontSize: 13 }}>
          Selected item: {JSON.stringify(selectedItem)}
        </Text>
      </View>
    </React.Fragment>
  );
};

const getStyles = () => ({
  spacer: {
    height: 50,
  },
  container: {
    borderColor: "red",
    borderWidth: 1,
  }
});

export default App;
```

**Comment by onmotion** [comment]
Hi!
Yes, here's the issue, but it's not about this module, but about the ScrollView on Android.

**Comment by IPWright83** [comment]
Do you know if there are any workarounds?

**Comment by onmotion** [comment]
Unfortunately no, seems like its platform limitation. In short, you shouldn't use background, shadow or zIndex on parent container. Also parent container should be 100% width and height of the screen. Pay attention on example (e.g. zIndex used only for iOS)

https://github.com/onmotion/react-native-autocomplete-dropdown/blob/388b5608425ab0c241b512b61c64168bd038cb74/example/App.js#L43

**Comment by IPWright83** [comment]
@onmotion thanks, I'll take a look and I'll see if I can make something work. Is there a relevant bug somewhere in react-native? I'm not 100% sure what to search for to track the relevant issue

**Comment by IPWright83** [comment]
I'm guessing this is the related bug? https://github.com/facebook/react-native/issues/29308#issuecomment-792864162

**Comment by yohaneswilliam12** [comment]
i think the problem is your parent view is too small to contain suggestionsListContainer, you still can click upper side of the suggestion because its still inside parent view

https://user-images.githubusercontent.com/49800188/133591990-55654be3-982b-4798-a7b2-3ba81d76fc05.mp4

the best solution i have is set the height of the parent container at least higher than suggestionListContainer height

**Comment by jas-chu** [comment]
> Unfortunately no, seems like its platform limitation. In short, you shouldn't use background, shadow or zIndex on parent container. Also parent container should be 100% width and height of the screen. Pay attention on example (e.g. zIndex used only for iOS)
> 
> https://github.com/onmotion/react-native-autocomplete-dropdown/blob/388b5608425ab0c241b512b61c64168bd038cb74/example/App.js#L43

Just to add up to this, it doesn't necessary have to be height 100%, but it has to be a height that covers all your dropdown, otherwise, the options that are outside that height will not be clickable. Here is an example, I painted the background yellow so we can see the height set, and how there are some options outside of it (which will not be clickable).

![image](https://user-images.githubusercontent.com/8629419/165998104-022a6bdc-9b5a-4d68-88dc-5a1a49c8f219.png)

**Comment by BossBele** [comment]
Sorted with:

https://github.com/onmotion/react-native-autocomplete-dropdown/issues/62#issuecomment-1520048916
