### ISSUE TITLE
Loading Indicator doesn't animate

### ISSUE THREAD

**Issue by IPWright83** [onmotion/react-native-autocomplete-dropdown#13]
I've found that when I set the loading prop to `true` the loading spinner appears, but it doesn't animate - it doesn't really convey the same message that it's loading when it's stationary.

![Bug](https://user-images.githubusercontent.com/1374775/134347544-94d8949a-c956-4322-b5c4-a2e5d4e626d7.gif)

**Comment by onmotion** [comment]
Could you please show your code for reproduce this?
Basically it rendered like `{loading && <ActivityIndicator color="#999" />}` and should show system ActivityIndicator
