### ISSUE TITLE
Can't put AutocompleteDropdown inside a <View>

### ISSUE THREAD

**Issue by jimzqw** [onmotion/react-native-autocomplete-dropdown#16]
If I put it inside a <view >then the drop-down list is messed up.

![image](https://user-images.githubusercontent.com/17305013/138220447-8d4ce814-0c29-421b-9294-a15f48efa7e3.png)

**Comment by saahiil-pny** [comment]
@onmotion I tried adding background colour to the `suggestionsListContainerStyle` prop, but it still shows the underlying View. Can we do something else to get this done?

**Comment by Mifayo** [comment]
@jimzqw have you found a solution ?

**Comment by cjbarth** [comment]
I'm also experiencing this issue.

**Comment by cjbarth** [comment]
I found that if I replace `<View />` with `<React.Fragment />` things start working again.

See https://reactjs.org/docs/fragments.html.

**Comment by Rushiraj-karm** [comment]
I am also facing same issue, 
<React.Fragment /> is also not working for me.
anyone has workaround for this ?

**Comment by onmotion** [comment]
Is this issue found on Android platform only? May be it related to https://github.com/onmotion/react-native-autocomplete-dropdown/issues/12 
In short, you should manually set height of the parent View with position absolute, otherwise child view cant stretch yourself

**Comment by onmotion** [comment]
Also, for iOS check out the example with zIndex
https://github.com/onmotion/react-native-autocomplete-dropdown/blob/b1e473068f82d01d84ba3e9b3e2787a87135bebb/example/componens/RemoteDataSetExample3.js#L44

**Comment by nehalhapani** [comment]
I am also facing same issue,
Add zIndex in <View /> can resolve issue for me.  put higher zIndex in first AutocompleteDropdown view, then add one less in second AutocompleteDropdown view.   

You can find example code here.

const [selectedItem, setSelectedItem] = useState(null)
<View style={{ zIndex: 99 }}>
          <AutocompleteDropdown
            clearOnFocus={false}
            closeOnBlur={true}
            closeOnSubmit={false}
            initialValue={{ id: "2" }} // or just '2'
            onSelectItem={setSelectedItem}
            dataSet={[
              { id: "1", title: "Alpha" },
              { id: "2", title: "Beta" },
              { id: "3", title: "Gamma" },
            ]}
          />
 </View>
<View style={{ zIndex: 98 }}>
          <AutocompleteDropdown
            clearOnFocus={false}
            closeOnBlur={true}
            closeOnSubmit={false}
            initialValue={{ id: "2" }} // or just '2'
            onSelectItem={setSelectedItem}
            dataSet={[
              { id: "1", title: "Alpha" },
              { id: "2", title: "Beta" },
              { id: "3", title: "Gamma" },
            ]}
          />
 </View>

**Comment by Rushiraj-karm** [comment]
Thanks for your update, it worked.
need your help again,  I want to change dropdown list item text color, 
can you please let me know how to do it ?

I tried render item, but if I set this than cannot autocomplete strings 
renderItem={(item, text) => (
            <Text style={{ color: "#fff", padding: 15 }}>{item.title}</Text>
          )}

Thanks,
Rushiraj

**Comment by onmotion** [comment]
> I tried render item, but if I set this than cannot autocomplete strings renderItem={(item, text) => ( <Text style={{ color: "#fff", padding: 15 }}>{item.title} )}

fixed #30 

Also now you can pass suggestionsListTextStyle for styling basic output items
