### ISSUE TITLE
Is there any way to change the 'Nothing found' text on current version or at least disable it entirely?

### ISSUE THREAD

**Issue by fmagesty** [onmotion/react-native-autocomplete-dropdown#18]
I see there is a new props to modify the Nothing found text on the Autocomplete but it (please correct me if I'm wrong on this) does not seem to be released yet.

So is there a way to disable it on the current version?

Tyvm

**Comment by onmotion** [comment]
Hi!

Just forgot to publish. Check it out now please

**Comment by fmagesty** [comment]
'emptyResultText' prop is fully functional with the new version! Thank you very much for this awesome feature!
