### ISSUE TITLE
Using renderItem cannot autocomplete strings

### ISSUE THREAD

**Issue by sjsj0612** [onmotion/react-native-autocomplete-dropdown#22]
When not using renderItem, It can autocomplete text strings. But on using renderItem, component cannot autocomplete strings. 

In example RemoteDataExample (not using renderItem)
![image](https://user-images.githubusercontent.com/28395557/146141566-ebfba13a-7166-46ae-a3f8-ca496058a8a2.png)

In example RemoteDataExample3 (using renderItem), you can see the difference between dropbox. 
![image](https://user-images.githubusercontent.com/28395557/146141766-60ff623c-cbd9-43d5-bc30-fc73cd7c0e50.png)

Very nice autocomplete-dropdown library! please fix this issue....

**Comment by Rushiraj-karm** [comment]
I am also facing same issue, 
anyone has workaround for this ?

**Comment by gauravkrp** [comment]
I'm also facing this issue and this limits me to using custom styles for render List Items. I want to use a custom font.

**Comment by tdido** [comment]
I can confirm this issue. simply adding the following lines breaks the autocomplete functionality:

```
  renderItem={(item, text) => (
    <Text style={{ color: colors.text, padding: 15 }}>{item.title}</Text>
  )}
```

**Comment by onmotion** [comment]
Hi guys!

I fix the issue and now renderItem will be filtered before the render by `title`.
But you also can filter it yourself by comparing item.title and text and return null if it shouldn't be rendered

**Comment by tdido** [comment]
Can confirm it now works for me. Thanks!
