### ISSUE TITLE
Unable to disable the input field of this dropdown

### ISSUE THREAD

**Issue by KishoreKumar18** [onmotion/react-native-autocomplete-dropdown#23]
I am trying to enable this dropdown based on a condition. But, I don't find a property to disable/enable the input field. Please let me know whether there is any way to implement

**Comment by onmotion** [comment]
Hi!

Maybe `textInputProps`?

**Comment by KishoreKumar18** [comment]
Yes, it worked. Thanks!!

**Comment by neeraj-tangariya** [comment]
maybe we can do something lke this
```
onOpenSuggestionsList={() => {
          console.log('onOpenSuggestionsList click-----------', isDisable);
          if (isDisable) {
            return dropdownController.current.close();
          }
        }}
```
here isDisable is a state in this case the dropdown will not open
