### ISSUE TITLE
Please report: Excessive number of pending callbacks: 501.

### ISSUE THREAD

**Issue by bayramn** [onmotion/react-native-autocomplete-dropdown#24]
I have over 450 author names array but throws a following warning:

Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code:

**Comment by mohdaatif** [comment]
I am facing the same issue, is there any workaround for this as the app getting stucked for more than 500 records

**Comment by onmotion** [comment]
Hey! I'll take a look soon. If you have some additional information that might be helpful, it would be nice to post it here.

**Comment by bayramn** [comment]
Thanks man. I ended up building my own dropdown autocomplete component and gets job done for now but will use later on.
