### ISSUE TITLE
Suggestion list is hiding behind another autocomplete object

### ISSUE THREAD

**Issue by hardikcc** [onmotion/react-native-autocomplete-dropdown#25]
I am trying to create a nested autocomplete objects. Strangely, the suggestionlist of first object is hiding below second object. I tried setting zIndex of suggestionlist container. Please guide.

<img width="321" alt="Screenshot 2022-03-09 at 11 18 26 PM" src="https://user-images.githubusercontent.com/16883134/157501172-eb300fae-3a08-487b-b9fe-6b15adda207f.png">

**Comment by onmotion** [comment]
Hi! I don't know the case, but maybe this example can help:

https://github.com/onmotion/react-native-autocomplete-dropdown/issues/16#issuecomment-1032502551

**Comment by matsmorot** [comment]
Any success? I tried the solution with `zIndex` but to no avail.

**Comment by onmotion** [comment]
Ok guys, for ios you have to manually define the zIndex of the dropdown containers.
So for example if you do smth like
```js
          <View style={[styles.section]}>
            <Text style={styles.sectionTitle}>First</Text>
            <AutocompleteDropdown
              dataSet={[
                { id: '1', title: 'Alpha' },
                { id: '2', title: 'Beta' },
                { id: '3', title: 'Gamma' },
              ]}
            />
          </View>
          <View style={[styles.section]}>
            <Text style={styles.sectionTitle}>Second</Text>
            <AutocompleteDropdown
              dataSet={[
                { id: '1', title: 'Alpha' },
                { id: '2', title: 'Beta' },
                { id: '3', title: 'Gamma' },
              ]}
            />
          </View>
```
you would see 
<img width="384" alt="Screenshot 2022-04-24 at 20 59 38" src="https://user-images.githubusercontent.com/12899080/164989990-2b4269e1-406a-48a5-9ec7-25e4f53d2fb0.png">

But if it change with calculated zIndex:

```js
          <View
            style={[styles.section, Platform.select({ ios: { zIndex: 10 } })]}>
            <Text style={styles.sectionTitle}>First</Text>
            <AutocompleteDropdown
              dataSet={[
                { id: '1', title: 'Alpha' },
                { id: '2', title: 'Beta' },
                { id: '3', title: 'Gamma' },
              ]}
            />
          </View>
          <View
            style={[styles.section, Platform.select({ ios: { zIndex: 9 } })]}>
            <Text style={styles.sectionTitle}>Second</Text>
            <AutocompleteDropdown
              dataSet={[
                { id: '1', title: 'Alpha' },
                { id: '2', title: 'Beta' },
                { id: '3', title: 'Gamma' },
              ]}
            />
          </View>
```

it will be rendered as expected
<img width="381" alt="Screenshot 2022-04-24 at 21 03 16" src="https://user-images.githubusercontent.com/12899080/164990163-7d2aa98d-3988-4636-97a3-8be229489472.png">

And the same, if you want render dropdown list to *top* direction, you should switch zIndexes respectively

More info about this behaviour: https://docs.expo.dev/ui-programming/z-index/

**Comment by matsmorot** [comment]
Thanks for your reply @onmotion. However, my problem with `zIndex` not working was because I wrapped the `<AutocompleteDropdown>` in a custom component (InputList here) to which I was sending in a `zIndex`. When I was then using two of these custom components this solution didn't work:

```
              <DataView group style={{ flexDirection: "column" }}>
                <View style={styles.selectContainerFullWidth}>
                  <InputList
                    key={"Customer"}
                    label={"Customer"}
                    listData={customerListData}
                    initialItem={initialCustomerData}
                    onSelect={setSelectedCustomerId}
                    zIndex={10}
                  />
                </View>
                <View style={styles.selectContainerFullWidth}>
                  <InputList
                    key={"Location"}
                    label={"Location"}
                    listData={locationListData}
                    initialItem={initialLocationData}
                    onSelect={setSelectedLocationId}
                    zIndex={9}
                  />
                </View>
              </DataView>
```

So, to solve it you have to put the `<AutocompleteDropdown>`s in the same view.
Maybe you are facing the same problem @hardikcc

**Comment by onmotion** [comment]
Seems it's not a typical case... Anyway, the root of a problem is a parent zIndex + flex. If you can make some research, PR highly appreciate

**Comment by hardikcc** [comment]
Thanks @onmotion, this method works perfect.
