### ISSUE TITLE
textInputProps shows as invalid prop in ESLint

### ISSUE THREAD

**Issue by dkoodev** [onmotion/react-native-autocomplete-dropdown#3]
When using typescript, the linter, or whatever checks the intrinsic props, shows an error saying that the textInputProps is an invalid prop, however if I run the react native app, it works!

<img width="1246" alt="Screen Shot 2021-06-18 at 3 45 11 PM" src="https://user-images.githubusercontent.com/13928397/122518460-2e6e3b00-d04c-11eb-8672-0a011d7e002f.png">

**Comment by dkoodev** [comment]
I think you just have to add the prop in `index.d.ts`

**Comment by onmotion** [comment]
Hi! You're right

**Comment by onmotion** [comment]
added in v1.1.3

Thanks
