### ISSUE TITLE
Clear the textInput Programatically

### ISSUE THREAD

**Issue by amujuruprasad** [onmotion/react-native-autocomplete-dropdown#31]
First of All Thank you for the wonderful library. I would like to clear the input programatically instead of clear button. can u please suggest me something to implement like this.

**Comment by onmotion** [comment]
Hi! It's mentioned in the example https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/example/components/RemoteDataSetExample3.js

You have to get access to the ref and after that you able call `clear()` method
