### ISSUE TITLE
SuggestionList inside a Modal is transparent and could not be selected in iOS

### ISSUE THREAD

**Issue by KishoreKumar18** [onmotion/react-native-autocomplete-dropdown#33]
I am facing an issue similar to the one mentioned in the /issues/16 in my **iOS**. This works as expected in Android.

The difference to the above mentioned issue is, here the dropdown is present inside a KeyboardAwareScrollView which is inturn present inside a Modal. I have tried React.Fragment for parent View and tried zIndex as well. But nothing seems to be helping. Or may be im applying it wrong. Please let me know if any further details needed to explain the issue. 

<img width="476" alt="Screenshot 2022-05-13 at 10 05 54 PM" src="https://user-images.githubusercontent.com/93245264/168329758-1c134631-7fb7-4ef2-bd2c-90095f07c3c4.png">

**Comment by onmotion** [comment]
Hi!

Maybe you can share some code?

**Comment by darksagas** [comment]
Please check [https://github.com/onmotion/react-native-autocomplete-dropdown#zindex-hell-on-ios](url) wrapping your input with a View component styled with zIndex may help.

**Comment by KishoreKumar18** [comment]
Yes, now its working fine. I was applying zIndex to the wrong parent view. Once I applied the zIndex to the View of AutoComplete component and the adjacent Views, it started working.!!!
