### ISSUE TITLE
Suggestion List not scrolling.

### ISSUE THREAD

**Issue by evicentin** [onmotion/react-native-autocomplete-dropdown#37]
Hello,

I implemented the following code, but my suggestion list is not scrolling. What could be wrong?

<AutocompleteDropdown
          debounce={600}
          emptyResultText={'Nenhum item encontrado.'}
          clearOnFocus={true}
          closeOnBlur={true}
          closeOnSubmit={false}
          useFilter={false}
          showChevron={false}
          loading={loading}
          dataSet={clientesList}
          onChangeText={handleOnChangeText}
          onClear={handleOnClearPress}
          onSelectItem={item => {
            item && setSelectedItem(item.id);
          }}
          renderItem={(item, text) => (
            <Text style={{padding: 15}}>{item.title}</Text>
          )}
          inputHeight={45}
          suggestionsListMaxHeight={Dimensions.get('window').height * 0.4}
          textInputProps={{
            placeholder: 'Digite 3 caracteres ou mais...',
            autoCorrect: false,
            autoCapitalize: 'none',
            style: {
              borderRadius: 15,
              backgroundColor: theme.gray[100],
              color: theme.gray[500],
              paddingLeft: 10,
            },
          }}
          inputContainerStyle={{
            backgroundColor: theme.gray[100],
            borderRadius: 15,
          }}
        />

**Comment by hardikcc** [comment]
How did you achieved this? I am using overflow: 'scroll' for flatListProps. This works in IOS but not in Android.
