### ISSUE TITLE
Highlighting the suggestion list text based on input isn't working for me

### ISSUE THREAD

**Issue by kristianskogberg** [onmotion/react-native-autocomplete-dropdown#40]
Hi, my suggestion list texts are not bolding based on user input (in this case 'saur' should be highlighted according to the examples). I also copied the provided examples but it's still not bolding for me.

![image](https://user-images.githubusercontent.com/106272614/180061078-81657d60-cac9-4275-817f-1c0532dde35b.png)

**Comment by onmotion** [comment]
The item must be either string or you have to implement logic by yourself through closure 
Check how renderItem works https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/src/ScrollViewListItem.js
