### ISSUE TITLE
Don't show suggestionList until some text is written

### ISSUE THREAD

**Issue by dantecarlo** [onmotion/react-native-autocomplete-dropdown#44]
How can I hide the suggestionList if the input text length is < than 3 for example.

I already try using onFocus prop with the useRef like this
```
const handleOnFocus = () => {
    dropdownController.current?.close();
 };
```
but it didn't work

**Comment by onmotion** [comment]
Hi! You could set the dataSet only when entering > 3. Have you checked remote dataSet examples? E.g.
 https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/example/components/RemoteDataSetExample2.js
