### ISSUE TITLE
Scroll doesn't work inside dropdown in v2

### ISSUE THREAD

**Issue by dpolkovnikov** [onmotion/react-native-autocomplete-dropdown#48]
Downgrade to version 1.2.1 solves the problem

https://github.com/onmotion/react-native-autocomplete-dropdown/commit/47aa26484c382c3384f75956bf1be0966c1ffc4a - the broken commit

**Comment by dpolkovnikov** [comment]
OR just pass `scrollEnabled: true` as flatListProps

**Comment by jeffelector** [comment]
not working for me,
tried to downgrade to 1.2.1 also did not work,
any suggestion? @dpolkovnikov ?
