### ISSUE TITLE
Not able to remove the border line in dropdown items

### ISSUE THREAD

**Issue by sangayt1997** [onmotion/react-native-autocomplete-dropdown#52]
Hello everyone I need to remove border line of the dropdown items.
 Even try using the renderItem to create new list items of drop down. But I can't find any way to remove the dropdown list border.

Please see the example below:

<img width="488" alt="Screen Shot 2022-10-11 at 13 09 06" src="https://user-images.githubusercontent.com/59992112/195020592-758b5939-410b-48a9-a038-da31a17f7ead.png">

Code:

import React, { useState } from 'react';
import { AutocompleteDropdown } from 'react-native-autocomplete-dropdown';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { styles } from './styles/autocomplete.styles';
import { Text } from 'native-base';
import { Dimensions, Platform } from 'react-native';

export function AlAutoComplete() {
  const [selectedItem, setSelectedItem] = useState();
  const dataset = [
    { id: '1', title: 'Alpha' },
    { id: '2', title: 'Beta' },
    { id: '3', title: 'Gamma' },
    { id: '4', title: 'Gamma' },
    { id: '5', title: 'Gamma' },
    { id: '6', title: 'Alpha' },
    { id: '7', title: 'Alpha' },
    { id: '8', title: 'Alpha' },
    { id: '9', title: 'Alpha' },
    { id: '10', title: 'Gamma' },
    { id: '11', title: 'Gamma' },
    { id: '12', title: 'Gamma' },
    { id: '13', title: 'Gamma' },
    { id: '14', title: 'Gamma' },
    { id: '15', title: 'Gamma' },
  ];

  return (
      <AutocompleteDropdown
        clearOnFocus={false}
        closeOnBlur={false}
        closeOnSubmit={false}
        showClear={false}
        initialValue={{ id: '1' }}
        onSelectItem={setSelectedItem}
        inputContainerStyle={styles.inputContainerStyle}
        suggestionsListMaxHeight={Dimensions.get('window').height * 0.5}
        dataSet={dataset}
      />
  );
}

export default AutoComplete;

**Comment by marjen0** [comment]
Hello, you could use `ItemSeparatorComponent` prop for that.

```javascript
<AutocompleteDropdown
    ItemSeparatorComponent={<View style={{ height: 0 }} />}
    ...
/>
```

**Comment by sangayt1997** [comment]
@marjen0 Thank you so much
