### ISSUE TITLE
Showing Multiple Drop Down

### ISSUE THREAD

**Issue by girish54321** [onmotion/react-native-autocomplete-dropdown#54]
Hi,
First Thanks for this Amazing Package works great

But May i know how can i show 2 DropDown

My Code 

<img width="340" src="https://user-images.githubusercontent.com/47414322/196403594-b368edaf-dad4-4d24-8498-003d2898630d.png"/>

``` 
<View style={{flex:1}}>
      <DropDown />
       <DropDown />
</View>

**Comment by onmotion** [comment]
Hey,

You need to set the proper zIndex of each according the direction, just check the examples

**Comment by girish54321** [comment]
Ok @onmotion will try.

**Comment by girish54321** [comment]
Hi,

I don't know how, but adding `zIndex` in `suggestionsListContainerStyle` props fixed the overlapping

My Code 

``` 
<AutocompleteDropdown
    suggestionsListContainerStyle={{ width: "99%", alignSelf: 'center', 
    borderBottomLeftRadius: 8, borderBottomRightRadius: 8, borderTopRightRadius: 0, 
    borderTopLeftRadius: 0, 
    position: 'absolute', zIndex: zIndexIos }}
/>

**Comment by girish54321** [comment]
Closing this 🙂.

**Comment by sangayt1997** [comment]
@girish54321  What is the value you assign zIndexIos?

**Comment by girish54321** [comment]
@sangayt1997 
Form Top of the screen start at 999 and at bottom 111
