### ISSUE TITLE
Prevent open on focus

### ISSUE THREAD

**Issue by verbowersock** [onmotion/react-native-autocomplete-dropdown#55]
Is there a way to prevent the dropdown from opening onFocus? I need it to only open when the user enters a search term.

**Comment by onmotion** [comment]
Hi

Just pass dataSet like in remote dropdown example https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/example/components/RemoteDataSetExample2.js

**Comment by orafoxtechnologies** [comment]
Hi @verbowersock Can you share example for this task. I'm using the dropdown Controller to handle this situation, but did not work proper.

Thanks!

**Comment by dhaval23996** [comment]
Hi @verbowersock Can you share example for this task. I'm using the dropdown Controller to handle this situation, but did not work proper.

Thanks!
