### ISSUE TITLE
ERROR  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.

### ISSUE THREAD

**Issue by rameshep1989** [onmotion/react-native-autocomplete-dropdown#56]
While focus the input it triggers the below error.

 ERROR  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.

Here is my code.
<KeyboardAwareScrollView keyboardShouldPersistTaps='always' enableOnAndroid={true} contentContainerStyle={{ flexGrow: 1 }}>            
        <AutoCompleteInput
                                name='cityId'
                                dataSet={cities}
                                placeholder='City'
                                disabled={!(isCityDisable || cities.length <= 0)}
                                titleKey='cityName'
                                titleId='cityId'
                                closeOnBlur={true}
                                emptyResultText='No city found'
                            />                    
  </KeyboardAwareScrollView>

**Comment by onlyhope** [comment]
I just hit a similar issue. "VirtualizedLists should never be nested inside plain ScrollViews [...]". Anyone have an idea of the best way to handle?

**Comment by onmotion** [comment]
Duplicate #36
