### ISSUE TITLE
How to use InputComponent to render a custom component like paper TextInput

### ISSUE THREAD

**Issue by verbowersock** [onmotion/react-native-autocomplete-dropdown#57]
How exactly do I render a custom TextInput like react-native-paper?

I attempted to render it with the InputComponent and receive an error: null is not an object (evaluating j.current.blur) when i click on the selection.

When I render with the render prop from react-native-paper TextInput, the selection overlaps the label.

Any help is appreciated.

Please find the snack below:

https://snack.expo.dev/29Lnl2f2-

**Comment by onmotion** [comment]
Hi

I guess you have to use component with forwardRef

**Comment by verbowersock** [comment]
sorry I read the docs on forwardRef but I am having a very hard time figuring out how to use it in this case. Could you please provide some pointers?

**Comment by onmotion** [comment]
https://snack.expo.dev/@onmotion/arrogant-marshmallows-fork

**Comment by verbowersock** [comment]
Oh it's that easy huh! I understand now. Thanks so much for your help.
