### ISSUE TITLE
Any ways to disabled the opening of Keyboard?

### ISSUE THREAD

**Issue by sangayt1997** [onmotion/react-native-autocomplete-dropdown#63]
Hello Everyone I need to disabled the keyboard opening when i click on the autocomplete textInput as in my situation I got some few value in the dropdown list.

**Comment by onmotion** [comment]
Hey

Not sure I understand your case right, but for example you can do like this 
```js
        textInputProps={{
          editable: false
        }}
```

or call `Keyboard.dismiss()` onFocus

**Comment by sangayt1997** [comment]
@onmotion Thank you for the response as I tried with your solution, I think for my use cases I have to use select input. So Closing this Issue.
