### ISSUE TITLE
Controller type error

### ISSUE THREAD

**Issue by frannale** [onmotion/react-native-autocomplete-dropdown#69]
Hi! I want to make an auto focus on the render component. I have an error using the controller of the component, about the ts types, if ignore the ts the code brokes on run with undefined error over the ref.

Im using the 2.1.0 version 

![Screenshot 2023-02-21 at 20 13 25](https://user-images.githubusercontent.com/28931796/220479974-728f872d-cf3c-4cf2-9e35-12069bb08e48.png)

**Comment by dk253** [comment]
I'm getting the same error on version 3.1.3.  What do I need to change?
