### ISSUE TITLE
Sometimes list items appear blank

### ISSUE THREAD

**Issue by tiliv** [onmotion/react-native-autocomplete-dropdown#7]
I've implemented a simple autocomplete box driven by a local dataset.  I memoize the list without dependencies, and the behavior of the search results seems inconsistent.  In the video I've attached, you can see me trying to search for `Artist`, which appears sometimes and not others, but I've confirmed that the blank row is still connected to the right list item (i.e., when I click on it, it does respond as I expect).

I can't figure out what makes it show or not, since you can see in the video that I do ultimately make it appear by just typing and backspacing a few times, selecting other items, etc.  It doesn't appear to be related to which item is currently selected.

https://user-images.githubusercontent.com/618184/130699866-b23976a8-c953-4d34-ad5d-1433ef907ad1.mov

I'm a fan of how good the default styling is out of the box, so I'd love to make this work.  Do you have any ideas?

I don't currently have time to make a fully reproducible demo, but the component is quiet simple:

```javascript
import React, { useState, useContext, useMemo } from 'react';
import { View } from 'react-native';
import { AutocompleteDropdown } from 'react-native-autocomplete-dropdown'

import DecksContext from 'CONTEXTS/decks';
import Card from './Card';

export default function CardFinder() {
  const { ownedCards } = useContext(DecksContext);

  const cardsList = useMemo(() => {
    return ownedCards.map(card => ({ id: card.card_id, title: card.title }));
  }, []);

  const [ cardId, setCardId ] = useState(null);

  return (
    <View>
      <AutocompleteDropdown
        onSelectItem={({ id }) => setCardId(id)}
        dataSet={cardsList}
      />
      {cardId ? (
        <Card id={cardId} />
      ) : null}
    </View>
  );
}
```

Version info:
```
"expo": "~42.0.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
"react-native-autocomplete-dropdown": "^1.1.4",
```

**Comment by onmotion** [comment]
Hi!

It's strange, but I can't reproduce this behaviour...

**Comment by tiliv** [comment]
I'm using this inside a BottomSheet component, which might be the source of trouble.  My BottomSheet requires the use their `BottomSheetTextInput` and `BottomSheetFlatList` inside of the popup sheet.

Repository: https://github.com/gorhom/react-native-bottom-sheet

I tried implementing my own local-only version of this component using those specialized components, and it seems to work fine.

The only idea I can offer is to allow props to override the TextInput component and FlatList component, by reference or by a render function that takes AutocompleteDropdown's default props.

Anyway, in short, no bug.

**Comment by onmotion** [comment]
Using the same (with gorhom bottom sheet) way in my project)
