### ISSUE TITLE
Updating text after selecting item fails to show in text input after keyboard is closed

### ISSUE THREAD

**Issue by shaunthium** [onmotion/react-native-autocomplete-dropdown#72]
After selecting an item, if I update the text field, the text will seem to be correctly updated in the text input. But after dismissing the keyboard, the text input will reset to the previously selected item, even though my onChangeText and onSelectItem functions capture the updated state. Purely updating the text input or selecting the item works fine.

Initially opening list:
<img width="274" alt="Screenshot 2023-03-08 at 12 14 13 AM" src="https://user-images.githubusercontent.com/10166415/223481201-d8f2ad5f-eb98-4c34-85f8-12df4adbcc0d.png">

Selecting item "AA":
<img width="259" alt="Screenshot 2023-03-08 at 12 14 47 AM" src="https://user-images.githubusercontent.com/10166415/223481431-2dd39a9d-ce4e-473a-b54b-6edb0f4c05c9.png">

Updating text input (text input field seems to have correctly updated text):
<img width="268" alt="Screenshot 2023-03-08 at 12 16 09 AM" src="https://user-images.githubusercontent.com/10166415/223482061-1dab7b9f-9b84-4047-bb4c-04bbc9b938dc.png">

After dismissing keyboard (text input field resets to last selected item "AA", even though my state has correctly captured the updated text of "AAbbb"):
<img width="263" alt="Screenshot 2023-03-08 at 12 17 03 AM" src="https://user-images.githubusercontent.com/10166415/223482453-0e35fbe5-7118-45e9-8cdb-7823d5656ff0.png">

Thank you.

**Comment by Joelis57** [comment]
I had a similar problem, which I solved by doing this:

```js
const dropdownController = useRef(null)

<AutocompleteDropdown
  [...]
  controller={(controller) => {
    dropdownController.current = controller
  }}
  onBlur={() => {dropdownController.current.setItem({ id: 'selectedIdHere', title: 'selectedTitleHere' })}}
  />
```

**Comment by shaunthium** [comment]
Thanks @Joelis57 , although that didn't fully work for me as my use case was to set the text in the input to an item that does not yet exist in the dataset. However taking note from your code I modified my code to the below which seems to have worked for my use case:

```
<AutocompleteDropdown
  [...]
  controller={(controller) => {
    dropdownController.current = controller
  }}
  onBlur={() => {dropdownController.current.setInputText(activity)}}
  textInputProps={{
    onSubmitEditing: () => {dropdownController.current.toggle()}
  }}
  />
```

Appreciate the help!
