### ISSUE TITLE
Nested scrollView

### ISSUE THREAD

**Issue by BSC-Win** [onmotion/react-native-autocomplete-dropdown#8]
I'm facing some issues when using this component inside a parent scrollView. Basically I can't scroll and also the keyboardAvoidView doesn't work too.

**Comment by onmotion** [comment]
Hi. Maybe its related to #12

**Comment by GuilleAntico** [comment]
Hi, just a heads up, I was having the same issue and found a workaround, maybe it's handy.  Basically, I've created a timer inside useRef, that hides the Keyboard after a second the user stops typing.  Very important to set  closeOnBlur={false}, it will keep the list open after the keyboard hides.

`
import React, {useEffect, useRef} from 'react';
import {
  AutocompleteDropdown,
  TAutocompleteDropdownItem,
} from 'react-native-autocomplete-dropdown';
import {Keyboard} from 'react-native';


const SelectInput = ({
options
}) => {
  const inputRef = useRef(null);
  const timer = useRef(null);

  return (
   <AutocompleteDropdown
        controller={controller => {
          inputRef.current = controller;
        }}
        onChangeText={() => {
          if (timer.current && timer.current) {
            clearInterval(timer.current);
          }
          timer.current = setTimeout(() => {
            Keyboard.dismiss();
          }, 1000);
        }}
        clearOnFocus={false}
        closeOnBlur={false}
        closeOnSubmit={false}
        dataSet={options}
      />
  );
};

export default React.memo(SelectInput);

`
