### ISSUE TITLE
Autocomplete dropdown(react-native-autocomplete-dropdown) was not working when it was wrapped inside react-native-keyboard-aware-scroll-view after react native upgrade from ^0.63.4" to "^0.71.7" 

### ISSUE THREAD

**Issue by bvenkateswararao** [onmotion/react-native-autocomplete-dropdown#85]
Following an upgrade in the Android emulator's debug mode, clicking on the Autocomplete dropdown field caused the app to crash. However, in normal mode, the app did not crash but instead displayed warnings. Running the same code on a Samsung device resulted in neither crashes nor warnings, but the scrolling functionality was not functioning as expected.
Packages used are below
 "react": "^18.2.0",
 "react-native": "^0.71.7",
"react-native-autocomplete-dropdown": "^3.0.2",
 "react-native-keyboard-aware-scroll-view": "^0.9.5",

**Comment by onmotion** [comment]
Could not reproduce. Tried change `KeyboardAvoidingView` to `KeyboardAwareScrollView` in the example, it works as expected without crashes

```js
<AutocompleteDropdownContextProvider>
      <SafeAreaView style={[backgroundStyle, { flex: 1 }]}>
        <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
        <KeyboardAwareScrollView style={styles.scrollContainer}>
          <View style={styles.container}>
            <Text style={styles.title}>Autocomplete dropdown</Text>
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Local list</Text>
              <LocalDataSetExample />
            </View>
//...            
          </View>
        </KeyboardAwareScrollView>
      </SafeAreaView>
    </AutocompleteDropdownContextProvider>
```
