### ISSUE TITLE
Error while running "Example" code

### ISSUE THREAD

**Issue by aravindasn** [onmotion/react-native-autocomplete-dropdown#89]
I have downloaded code and trying to run "example" and getting following error:
Failed to construct transformer:  Error: ENOENT: no such file or directory, watch 'C:\Users\alexandrkozhevnikov\projects\react-native-autocomplete-dropdown'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2301:34)
    at NodeWatcher._watchdir (C:\CodeSa

 **Changed Package.json entry for "...autocomplete..." to use version 3.0.2"**
But still getting the same error.
1. ran "npm install"--> screenshot 1
2. ran "npm run android"--> screenshot 2
3. Error --> screenshot 2

**Please advise**

![image](https://github.com/onmotion/react-native-autocomplete-dropdown/assets/45733601/3d72625c-de2a-4862-b5fb-94c1a427b883)

![image](https://github.com/onmotion/react-native-autocomplete-dropdown/assets/45733601/95d5849a-6c5a-41a2-8edd-b84200179f44)

![image](https://github.com/onmotion/react-native-autocomplete-dropdown/assets/45733601/7e939cf8-4e30-499b-a5ee-4dab5cf025a3)

Here is the complete error:

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒

Failed to construct transformer:  Error: ENOENT: no such file or directory, watch 'C:\Users\alexandrkozhevnikov\projects\react-native-autocomplete-dropdown'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2301:34)
    at NodeWatcher._watchdir (C:\CodeSamples\react-native-autocomplete-dropdown-main\example\node_modules\metro-file-map\src\watchers\NodeWatcher.js:145:24)
    at new NodeWatcher (C:\CodeSamples\react-native-autocomplete-dropdown-main\example\node_modules\metro-file-map\src\watchers\NodeWatcher.js:43:10)
    at createWatcherBackend (C:\CodeSamples\react-native-autocomplete-dropdown-main\example\node_modules\metro-file-map\src\Watcher.js:205:23)
    at Array.map (<anonymous>)
    at Watcher.watch (C:\CodeSamples\react-native-autocomplete-dropdown-main\example\node_modules\metro-file-map\src\Watcher.js:233:27)
    at HasteMap._watch (C:\CodeSamples\react-native-autocomplete-dropdown-main\example\node_modules\metro-file-map\src\index.js:1014:25)
    at C:\CodeSamples\react-native-autocomplete-dropdown-main\example\node_modules\metro-file-map\src\index.js:369:20
    at async DependencyGraph.ready (C:\CodeSamples\react-native-autocomplete-dropdown-main\example\node_modules\metro\src\node-haste\DependencyGraph.js:99:5) {
  errno: -4058,
  syscall: 'watch',
  code: 'ENOENT',
  path: 'C:\\Users\\alexandrkozhevnikov\\projects\\react-native-autocomplete-dropdown',
  filename: 'C:\\Users\\alexandrkozhevnikov\\projects\\react-native-autocomplete-dropdown'
}
                Welcome to Metro v0.73.9
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

**Comment by onmotion** [comment]
Hi, please try to change your absolute path here https://github.com/onmotion/react-native-autocomplete-dropdown/blob/1f2116310853c7df6a3f957d36d26d545b0ebc28/example/metro.config.js#L8

**Comment by aravindasn** [comment]
Hi,
 Thank you for looking into this. In order to set the packagePath to local value, I ran npm install on this folder (react-native-autocomplete-dropdown folder) and it failed. 
**Please advise**
I am getting following error:
PS C:\CodeSamples\react-native-autocomplete-dropdown-main> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-native-autocomplete-dropdown@3.0.2
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.14.0" from the root project
npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/eslint-plugin@5.62.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     peerOptional @typescript-eslint/eslint-plugin@"^5.0.0" from eslint-plugin-unused-imports@2.0.0
npm ERR!     node_modules/eslint-plugin-unused-imports
npm ERR!       dev eslint-plugin-unused-imports@"^2.0.0" from the root project
npm ERR!   1 more (@typescript-eslint/parser)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.0.0" from eslint-plugin-unused-imports@2.0.0
npm ERR! node_modules/eslint-plugin-unused-imports
npm ERR!   dev eslint-plugin-unused-imports@"^2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\<<User>>\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<<User>>\AppData\Local\npm-cache\_logs\2023-08-06T08_01_55_971Z-debug-0.log
PS C:\CodeSamples\react-native-autocomplete-dropdown-main>
